apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-jlprgl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-jlprgl
    app.kubernetes.io/part-of: jvm-build-suite-application-yvtp
  name: jvm-build-suite-component-jlprgl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-jlprgl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-jlprgl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-ehyd-tenant/jvm-build-suite-application-yvtp/jvm-build-suite-component-jlprgl@sha256:be6c7cb254a32a131b1b09bdce894c425636a27d4a4df38bc7714ed2ae16d43b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
